# Generated by Django 2.0.5 on 2018-07-12 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20180712_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'galleries'},
        ),
    ]
